export const actionTypes = {
  GET_MENU_LIST: 'GET_MENU_LIST',
  GET_MENU_LIST_SUCCESS: 'GET_MENU_LIST_SUCCESS',

  GET_PARTNERS_MENU_LIST: 'GET_PARTNERS_MENU_LIST',
  GET_PARTNERS_MENU_LIST_SUCCESS: 'GET_PARTNERS_MENU_LIST_SUCCESS',
  GET_PARTNERS: 'GET_PARTNERS',
  GET_PARTNERS_SUCCESS: 'GET_PARTNERS_SUCCESS',
  GET_OFFERS: 'GET_OFFERS',
  GET_OFFERS_SUCCESS: 'GET_OFFERS_SUCCESS',
  GET_BONUS: 'GET_BONUS',
  GET_BONUS_SUCCESS: 'GET_BONUS_SUCCESS',

  GET_PRIVILEGE: 'GET_PRIVILEGE',
  GET_PRIVILEGE_SUCCESS: 'GET_PRIVILEGE_SUCCESS',
};
